jobs:
  main:
    requires: [~pr, ~commit]
    image: centos:latest
    steps:
      - env: env
    annotations:
      screwdriver.cd/repoManifest: https://github.com/Filbird/v4-manifest-test.git
    
