jobs:
  blocked: 
    requires: [~pr, ~commit]
    blockedBy: [~main]
    image: node:10
    steps:
      - env: env;
  main:
    requires: [~pr, ~commit]
    image: node:10
    steps:
      - env: env; sleep 60;
