jobs:
  main:
    requires: [~pr, ~commit]
    image: node:8
    steps:
      - sleep: sleep 5000
    annotations:
      screwdriver.cd/repoManifest: https://github.com/Filbird/v4-manifest-test.git
    
